### ISSUE TITLE
'Minimal' search on resource groups will trigger assertion failure if there are no RGs

### ISSUE THREAD

**Issue by desbonnm** [HewlettPackard/python-opsramp#127]
Calling the resource groups minimal API (https://develop.opsramp.com/docs/v2/resource-management/tenants-clientid-devicegroups-minimal) on an opsramp tenant that has no resource groups results in an empty response from the API.

This results in an assertion failure when calling via python-opsramp:

```
>>> import opsramp.binding
>>> ormp = opsramp.binding.connect(OPSRAMP_URL, OPSRAMP_KEY, OPSRAMP_SECRET)
>>> tenant = ormp.tenant(OPSRAMP_TENANT_ID)
>>> tenant.resource_groups().minimal()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/desbonne/src/github.com/HewlettPackard/python-opsramp/opsramp/resource_groups.py", line 58, in minimal
    return list2ormp(simple_list)
  File "/home/desbonne/src/github.com/HewlettPackard/python-opsramp/opsramp/resources.py", line 34, in list2ormp
    assert isinstance(result_obj, list)
AssertionError
```
The [list2ormp()](https://github.com/HewlettPackard/python-opsramp/blob/dbaab0bca15f7982692b0a078006d31ec08993db/opsramp/resources.py#L25) function cannot handle the empty response.

**Comment by jofegan** [comment]
Okay that's great thanks for the report. The assert is doing its job by alerting us that the function is being called with something that is neither a dict nor a list, which are the only types it's able to handle. Thanks for the PR I will have a look.
